Cleaning Log I

Import libraries (panda & seaborn)

load .csv file containing data and store in variable, 'df'

In [1]:
import pandas as pd
import seaborn as sns

df = pd.read_csv("messy_sales.csv")

Cleaning Log II

dispay the number of rows & columns, given by the .shape() function

In [2]:
df.shape

(300, 6)

Cleaning Log III

dispay the first 10 rows, given by the .head(10) function

In [3]:
df.head(10)

   order_id        date   product  price  qty    zip
0      1254  04/06/2026       mug  11.36    4  60614
1      1057  2026-05-30   charger  14.79    3  30303
2      1150  05/06/2026       mug   5.50    1  10001
3      1066  05/30/2026  notebook    NaN    1  98101
4      1114  04/06/2026    webcam  45.59    4  90405
5      1280  04/22/2026   pen set    NaN    4  30303
6      1204  04/18/2026   charger   8.41    2   2134
7      1249  2026-05-15  keyboard  75.04    4  90405
8      1037  2026-05-19       mug   9.31    2  60614
9      1177  2026-05-13       mug  10.11    3  90210

Cleaning Log IV

dispay the data types of the columns, given by the .dtypes() function

In [4]:
df.dtypes

order_id      int64
date            str
product         str
price       float64
qty           int64
zip           int64
dtype: object

Cleaning Log V

There are at least three problems that I can already see in this data:
1. There are rows, that are either blank entries or characters not representing a number, in the price column. Those values are represented by "NaN".
2. The dates are in mixed format.
3. The zip column has fields of different lenghts. Padding with zeroes could be implemented.

Cleaning Log VI

dispay the blank entries of the columns, given by the .isna().sum() function

In [5]:
df.isna().sum()

order_id     0
date         0
product      0
price       12
qty          0
zip          0
dtype: int64

Cleaning Log VII

1. Fill the missing prices using the 'median' statistic that resists skewed prices. 
2. Print the fill value I used and record the fill value for your cleaning log.
3. I will show that there are 0 missing prices afterwards.

In [6]:
fill_value = df["price"].median()
print(f'The fill value represented by the medial of the price column is {fill_value}.')
df["price"] = df["price"].fillna(fill_value)
df.isna().sum()

The fill value represented by the medial of the price column is 37.53.

order_id    0
date        0
product     0
price       0
qty         0
zip         0
dtype: int64

Cleaning Log VIIi

Here, I show that there are 8 duplicates in the data frame before the .drop_duplicates() function.

In [7]:
print(df.duplicated().sum())
df = df.drop_duplicates()

8

Cleaning Log IX

Via the shape() function, I now show the quantity of rows of the data frame are now 292. Down 8 from the original 300 rows shown earlier.

In [8]:
df.shape

(292, 6)

Cleaning Log X

Here, I pad the missing digits in the entries per the 'zip' column. I used the parameter 5 since the zip code has 5 digits in our data. I then printed the data frame to show the results of padding, when comparing with the other data frames printed earllier.

In [9]:
df["zip"] = df["zip"].astype(str).str.zfill(5)
print(df)

     order_id        date   product  price  qty    zip
0        1254  04/06/2026       mug  11.36    4  60614
1        1057  2026-05-30   charger  14.79    3  30303
2        1150  05/06/2026       mug   5.50    1  10001
3        1066  05/30/2026  notebook  37.53    1  98101
4        1114  04/06/2026    webcam  45.59    4  90405
..        ...         ...       ...    ...  ...    ...
294      1103  2026-04-21   pen set  16.47    3  90405
296      1067  2026-04-27  backpack  37.93    5  90210
297      1025  2026-04-27  keyboard  47.30   -2  02116
298      1196  04/25/2026   pen set   8.79    3  90405
299      1175  2026-05-16       mug   4.63    4  10001

[292 rows x 6 columns]

Cleaning Log XI

Since there were mixed formatting in the 'date' column of our data, I used the .to_dateframe() function and its parameters to make the formatting uniform.

In [10]:
df["date"] = pd.to_datetime(df["date"], format="mixed")
print(df)

     order_id       date   product  price  qty    zip
0        1254 2026-04-06       mug  11.36    4  60614
1        1057 2026-05-30   charger  14.79    3  30303
2        1150 2026-05-06       mug   5.50    1  10001
3        1066 2026-05-30  notebook  37.53    1  98101
4        1114 2026-04-06    webcam  45.59    4  90405
..        ...        ...       ...    ...  ...    ...
294      1103 2026-04-21   pen set  16.47    3  90405
296      1067 2026-04-27  backpack  37.93    5  90210
297      1025 2026-04-27  keyboard  47.30   -2  02116
298      1196 2026-04-25   pen set   8.79    3  90405
299      1175 2026-05-16       mug   4.63    4  10001

[292 rows x 6 columns]

In [11]:
df.shape

(292, 6)

Cleaning Log XII

I show the data type of the 'date' column after making them uniform, above.

In [12]:
df.dtypes

order_id             int64
date        datetime64[us]
product                str
price              float64
qty                  int64
zip                    str
dtype: object

Cleaning Log XIII

Here, I filter the data via the 'qty' column to show the negative values.

In [13]:
print(df[df["qty"] <= 0])

     order_id       date    product  price  qty    zip
202      1140 2026-04-18     webcam  38.69   -5  98101
262      1233 2026-05-09  desk lamp  22.64   -4  10001
297      1025 2026-04-27   keyboard  47.30   -2  02116

Cleaning Log XIV

Here, I used he .to_csv() function to change the format of the data frame to .csv format. I then save the file and printed the .csv file to show the product of the data processing.

In [14]:
df.to_csv("sales_clean.csv", index=False)

df = pd.read_csv("sales_clean.csv", header=None)
df

            0           1         2      3    4      5
0    order_id        date   product  price  qty    zip
1        1254  2026-04-06       mug  11.36    4  60614
2        1057  2026-05-30   charger  14.79    3  30303
3        1150  2026-05-06       mug    5.5    1  10001
4        1066  2026-05-30  notebook  37.53    1  98101
..        ...         ...       ...    ...  ...    ...
288      1103  2026-04-21   pen set  16.47    3  90405
289      1067  2026-04-27  backpack  37.93    5  90210
290      1025  2026-04-27  keyboard   47.3   -2  02116
291      1196  2026-04-25   pen set   8.79    3  90405
292      1175  2026-05-16       mug   4.63    4  10001

[293 rows x 6 columns]